### ISSUE TITLE
Chrome repaint jidderish

### ISSUE THREAD

**Issue by Pelsin** [Vinnovera/vinnovera.github.io#1]
![vino](https://cloud.githubusercontent.com/assets/5345892/6963612/9633a2ec-d941-11e4-9052-c2162a2e9729.gif)

Noterade att eran logga gjorde en repaint i chrome on scroll, fina chrome ;P
Tror att transform hack skulle lösa det, tvinga GPU acc:
```
.to-top{
  -webkit-transform: translateZ(0);
}
```

**Comment by gewfy** [comment]
Alltså! :heart:

**Comment by pstenstrm** [comment]
+1

**Comment by gewfy** [comment]
Pushed to vinnovera.se
